name: "Build Validation"

on:
  push:
    branches: [master]
    paths:
      - "**/*.c"
      - "**/*.h"
      - "**/CMakeLists.txt"
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**/*.c"
      - "**/*.h"
      - "**/CMakeLists.txt"
  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  build:
    name: Build on ${{ matrix.platform }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: Linux
            arch: x64

          - os: ubuntu-24.04-arm
            platform: Linux
            arch: arm64

          - os: macos-13
            platform: macOS
            arch: Intel

          - os: macos-latest
            platform: macOS
            arch: arm64

          - os: windows-latest
            platform: Windows
            arch: x64

          - os: windows-11-arm
            platform: Windows
            arch: arm64

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          submodules: "recursive"

      - name: Prepare Project Build
        uses: ./.github/actions/prepare-project-build

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: CMAKE_BUILD_TYPE=Release
          build-args: --config Release --target ${{ env.PROJECT_NAME }}

      - name: Upload Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            build/**/${{ env.PROJECT_NAME }}
            build/**/${{ env.PROJECT_NAME }}.exe
          if-no-files-found: error
          retention-days: 1
          compression-level: 9
