name: "Release Artifacts"

on:
  workflow_run:
    workflows: ["Build Validation"]
    types: [completed]
    branches: [master]
  workflow_dispatch:

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  release:
    name: Upload to GitHub Release
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: write

    env:
      SOURCE_DIR: "artifacts"
      OUTPUT_DIR: "release-assets"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Prepare Release Assets
        id: prep_assets
        uses: ./.github/actions/prepare-release-assets
        with:
          source-dir: ${{ env.SOURCE_DIR }}
          output-dir: ${{ env.OUTPUT_DIR }}

      - name: Update dev Tag
        run: |
          git tag dev ${{ github.sha }}
          git push origin "refs/tags/dev" --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev
          name: Continuous dev Build
          body: Automated build from commit ${{ github.sha }}
          prerelease: true
          preserve_order: true
          files: ${{ env.OUTPUT_DIR }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
